apiVersion: synthesis/v1
kind: audit.api-endpoint
metadata:
  name: api-get-synthesis-session
spec:
  displayName: "get_synthesis_session"
  endpointType: mcp-tool
  toolName: "get_synthesis_session"
  description: "Get information about the current MCP session."
  permissionRequired: tenant_user
  componentRef: "!name ss-mcp-server"
